### ISSUE TITLE
Many website die

### ISSUE THREAD

**Issue by win123139** [billythekids/plugin.video.bimozie#42]
some website can not watch anymore like phimmoi or can see but cannot play like hayghe
can you add phimgiz.net ?

**Comment by billythekids** [comment]
fixed

**Comment by bathien1408** [comment]
> 
> 
> fixed

wow, thank you very much . But phimmoizz and bilutvs still cannot play the video when choosing. Can you check
